fix(gradle): Avoid model name classpath clashes with `GradleInspector`
In 287844e, the model used for Gradle project analysis was duplicated
between the legacy `Gradle` and the new `GradleInspector` analyzers,
however the interface names stayed the same. As the CLI has all classes
from all distributed plugins on the classpath, this resulted in a name
clash which, depending on classpath ordering, resulted in a
`NoSuchMethodError`. Solve this by prefixing interface names from the
legacy `Gradle` analyzer.

Signed-off-by: Sebastian Schuberth <sebastian@doubleopen.io>