MavenSupport: Do not fail on missing checksum
If the checksum cannot be retrieved from the server the function falls
back to using an empty string instead. This was broken since eeea7ec,
because calling `Hash.create()` with an empty string will fail to verify
the checksum with a message like this:

java.lang.IllegalArgumentException: '' is not a SHA-1 hash.

Instead, check if the checksum is blank and use `Hash.NONE` in this
case.

Signed-off-by: Martin Nonnenmacher <martin.nonnenmacher@here.com>