ResolvableError: Eliminate some dependencies and use properties
Using immutable properties instead of functions makes it clear that the
(returned) values won't change. The creation of the description string
thus gets moved into the mapper which is exactly its responsibility.
Finally without depending on OrtIssue and ErrorResolution the class
becomes reusable, e.g. for a new error resolution type which is
gonna be introduced in a following change.

Signed-off-by: Frank Viernau <frank.viernau@here.com>