ResolvableError: Rename to ResolvableIssue
Recently the class 'Error' got renamed to 'OrtIssue'. This change
aligns the naming.

Signed-off-by: Frank Viernau <frank.viernau@here.com>