deps(docker): Pin setuptools version to 74.1.3
Version 75.0.0 of setuptools adds a dependency on jaraco.collections [1]
which causes the following error when running python-inspector [2]:

    ImportError: cannot import name 'splat' from 'jaraco.functools'

[1]: https://setuptools.pypa.io/en/latest/history.html#v75-0-0
[2]: https://github.com/aboutcode-org/python-inspector/issues/190

Signed-off-by: Martin Nonnenmacher <martin.nonnenmacher@bosch.com>