analyzer: Convert GStrings to plain Strings in two more missing places
This should avoid the

    IllegalArgumentException: java.lang.String is not an interface

error.