Travis: Make MercurialTest pass again
MercurialTest started to fail with

    abort: error: _ssl.c:510: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number

as Bitbucket disabled support for TLSv1 and TLSv1.1 [1]. In order to fix
this we need Python 2.7.9 or newer [2], but the Trusty image does only
offer Python 2.7.6. So an upgrade to the Xenial image is needed, which
on the other hand only comes with Java 10 or 11 (default) [3]. As even
the latest version of Android's sdkmanager seems to have problems with
Java 11, use Java 10 instead. Java 9 and above do not contain the JAXB
APIs anymore in the default classpath, so add them manually for
sdkmanager to work [4]. Finally, make Java use the system's certificate
store instead of the less complete OpenJDK store to allow HTTPS
downloads [5].

[1] https://bitbucket.org/blog/deprecating-tlsv1-tlsv1-1-2018-12-01
[2] https://mercurial-scm.org/wiki/SecureConnections
[3] https://blog.travis-ci.com/2018-11-08-xenial-release
[4] https://stackoverflow.com/a/43574427/1127485
[5] https://www.deps.co/guides/travis-ci-latest-java

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@here.com>