build(detekt-rules): Depend on `common-utils` only instead of `test-utils`
As of 3401ac3, the `test-utils` project depends on the rather large (in
terms of dependencies) `downloader` project, which in turn has a
transitive dependency on `org.apache.sshd:sshd-sftp`. For some reason,
Detekt 1.23.0 triggers a `NoSuchMethodError` in `SftpFileSystemProvider`
code that tries to use SLF4J. Work around that issue by "reducing" the
dependency on `test-utils` to just its `common-utils` dependency as
actually no test utils are needed in the `detekt-rules` project.

Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>