Error: Only use Linux line breaks when serializing the message
Add a custom Jackson serializer which convert "\r\n" and "\r" line breaks
into "\n" when serializing the Error class.