Unshallow the jGnash submodule
GitHub does not support this and says:

    error: Server does not allow request for unadvertised object
    2aa4cce7d7fd46164030f2b4d244c4b89e77f722

Change-Id: Ic9ccb7f728024267dcf1eb79779e8ed4544086ae