test(common-utils): Add a test for deleting files with bogus names
See [1] for the original source of the file which contains Unicode
characters that cannot be mapped to UTF-8, and thus cannot easily be
accessed / deleted on systems with a UTF-8 locale. Neither can such
files be created by the JVM in order to test deleting them.

A symptom when coming across such files is that e.g. Python programs fail
[2] with

    UnicodeEncodeError: 'utf-8' codec can't encode characters in position
    58-59: surrogates not allowed

and GitHub action JavaScript code fails [3] with

    Error: ENOENT: no such file or directory, lstat
    'ort/utils/common/src/test/assets/unmappable-characters/testu��es.txt'

when trying to commit such a file to this repository, which is why a
fork of the original repository is cloned at test runtime instead.

[1]: https://github.com/fshost/node-dir/tree/a57c3b1b571dd91f464ae398090ba40f64ba38a2/test/fixtures/testdir5
[2]: https://github.com/oss-review-toolkit/ort/actions/runs/10689495536/job/29631720587#step:4:48
[3]: https://github.com/oss-review-toolkit/ort/actions/runs/10689645654/job/29632221061#step:3:88

Signed-off-by: Sebastian Schuberth <sebastian@doubleopen.org>