docs(jenkins): Clarify that the credentials type should be for HTTP
Later steps use the `usernamePassword()` pipeline function [1] which
assumes credentials to be composed of a username and password for HTTP
authentication. Clarify this to avoid users specifying e.g. SSH
credentials which would result in

    ERROR: Credentials 'jenkins-ssh' is of type 'SSH Username with private
    key' where 'com.cloudbees.plugins.credentials.common.StandardUsername
    PasswordCredentials' was expected

[1]: https://www.jenkins.io/doc/pipeline/steps/credentials-binding/

Signed-off-by: Sebastian Schuberth <sebastian@doubleopen.org>