Stop using the experimental time API
For some reason some usages of the experimental time API suddenly fail
with `java.lang.NoSuchMethodError: kotlin.time.TimeMark.elapsedNow()D`.
Remove all usage of the experimental time API until the reason is found.

Signed-off-by: Frank Viernau <frank.viernau@here.com>