Gradle: Upgrade Maven resolver to version 1.3.3
The recent upgrade to 1.3.2, see 2e9eb96, broke the analyzer because that
release has accidentally been built with Java 11 rendering it unusable for
Java 8 which we currently use, see:

https://issues.apache.org/jira/browse/MRESOLVER-67

As result the analyzer runs into the following consistently:

java.lang.NoSuchMethodError:
  java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;

As that problem has already been addressed with the release of
version 1.3.3 fix the issue by upgrading again instead of reverting
to 1.3.1. It is now ensured that the release is done with Java 8, see:

https://github.com/apache/maven-resolver/commit/fff273068617c0e133fb62a70bc71e8968db199a

No official release note found, for the changes see:

https://github.com/apache/maven-resolver/compare/maven-resolver-1.3.2...maven-resolver-1.3.3

Signed-off-by: Frank Viernau <frank.viernau@here.com>