Gradle: Upgrade Maven resolver to version 1.3.3
The recent upgrade to 1.3.2, see 2e9eb96, broke the analyzer because that
release has accidentally been built with Java 11 rendering it unusable for
Java 8 which we currently use, see:

https://issues.apache.org/jira/browse/MRESOLVER-67

As result the analyzer runs into the following consistently:

java.lang.NoSuchMethodError:
  java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;

Which is why we reverted to version 1.3.1 in 26bb726 as version 1.3.3
was not yet mirrored at that time. But now it is, so again upgrade to
version 1.3.3.

No official release notes found, for the changes see:

https://github.com/apache/maven-resolver/compare/maven-resolver-1.3.1...maven-resolver-1.3.3

Signed-off-by: Frank Viernau <frank.viernau@here.com>