GitRepo: Downgrade repo to 2.13.8
For all 2.14 releases of repo until the current stable release 2.14.2
running sync with the `--fetch-submodules` option fails, for example for
the project used in `GitRepoFunTest` with these errors:

```
$ repo sync -c --force-sync --fetch-submodules

Fetching: 100% (2/2), done in 4.304s
Garbage collecting: 100% (2/2), done in 0.004s
Fetching: 100% (2/2), done in 0.010s
Garbage collecting: 100% (2/2), done in 0.004s
error: submodules/commons-text/: Cannot checkout oss-review-toolkit/ort-test-data-git-submodules/commons-text due to missing network sync; Run `repo sync -n oss-review-toolkit/ort-test-data-git-submodules/commons-text` first.
error: Cannot checkout oss-review-toolkit/ort-test-data-git-submodules/commons-text
error: submodules/test-data-npm/: Cannot checkout oss-review-toolkit/ort-test-data-git-submodules/test-data-npm due to missing network sync; Run `repo sync -n oss-review-toolkit/ort-test-data-git-submodules/test-data-npm` first.
error: Cannot checkout oss-review-toolkit/ort-test-data-git-submodules/test-data-npm

error: Unable to fully sync the tree.
error: Checking out local projects failed.
Failing repos:
submodules/commons-text
submodules/test-data-npm
Try re-running with "-j1 --fail-fast" to exit at the first error.
```

This issue does not occur with version 2.13.8, and also not with the
current master branch. Therefore temporarily downgrade to 2.13.8 with
the hope that the next release works again.

Signed-off-by: Martin Nonnenmacher <martin.nonnenmacher@here.com>