fix(bundler): Resolve dependencies from optional groups
These dependencies get still installed but are loaded only on demand.
This fixes an error like

    NoSuchElementException: Key rubocop is missing in the map.

which was caused by the `spec` map not containing all root
`dependencies`.

Signed-off-by: Sebastian Schuberth <sebastian@doubleopen.io>