Revert "Gradle: Upgrade kotlinx.html to version 0.7.2"
This reverts commit 39c4e57effee7dee8383db3618056dd61970d0f6.

For some reason the upgrade makes some usages of the experimental time
API fail with:

java.lang.NoSuchMethodError: kotlin.time.TimeMark.elapsedNow()D``.

Signed-off-by: Martin Nonnenmacher <martin.nonnenmacher@here.com>