fix(docker): Install `wheel` after a potential `pip` upgrade
If `pip` was upgraded, `wheel` needs to be installed for that new
version. This fixes the `conan` installation to complain about

    error: invalid command 'bdist_wheel'

Signed-off-by: Sebastian Schuberth <sebastian@doubleopen.org>