fix(Poetry): Do not fail if "dev" dependency group is absent
The analyzer fails with [1]. Fix this by using the options such that
only the "main" scope is referred to, which is the only group guaranteed
to exist.

[1] Poetry failed to resolve dependencies for path 'poetry.lock':
    IOException: Running 'poetry export --without-hashes
      --format=requirements.txt
      --only=dev' in '/project' failed with exit code 1:

Signed-off-by: Frank Viernau <frank_viernau@epam.com>