Conan: Pass dummy compiler settings to the `info` command
For yet unknown reasons, Conan started to require these compiler
settings to be set, or otherwise fails e.g. with

    ERROR: libcurl/7.79.1: 'settings.compiler' value not defined

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>