PIP: Pin the pip version used in the virtualenv
As it turns out, recent versions of virtualenv do not pin a hard-coded
version of pip anymore. Because a new pip version 10.0.0 was just
released, our virtualenv started using it, but that version is
incompatible with pipdeptree due to

AttributeError: 'module' object has no attribute 'get_installed_distributions'

So ensure the last working version 9.0.3 of pip is installed.