azure-pipelines: Bump the LinuxTest cache key
This hopefully gets rid of this bogus build error:

    > Task :reporter-web-app:yarnBuild FAILED
    yarn run v1.22.10
    $ rescripts build
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    node:internal/modules/cjs/loader:936
      throw err;
      ^

    Error: Cannot find module '../scripts/build'
    Require stack:
    - /home/vsts/work/1/s/reporter-web-app/node_modules/.bin/rescripts
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
        at Function.resolve (node:internal/modules/cjs/helpers:108:19)
        at Object.<anonymous> (/home/vsts/work/1/s/reporter-web-app/node_modules/.bin/rescripts:35:25)
        at Module._compile (node:internal/modules/cjs/loader:1101:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        at node:internal/main/run_main_module:17:47 {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/home/vsts/work/1/s/reporter-web-app/node_modules/.bin/rescripts'
      ]
    }
    error Command failed with exit code 1.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>