Error: Only use Linux line breaks when serializing the message
Add a custom Jackson serializer which converts "\r\n" and "\r" line breaks
into "\n" when serializing the Error class.

This ensures that we get the same formatting of error messages across
different platforms.