Revert "Gradle: Enable parallel compilation of independent source sets"
Disable parallel compilation of source sets, because it causes frequent
compilation errors under Linux, e.g. "java.lang.NoClassDefFoundError: Could
not initialize class kotlin.Unit".

This reverts commit eaaf313e9e36c0edc367723ffc198440811f9d4e.

Signed-off-by: Martin Nonnenmacher <martin.nonnenmacher@here.com>