Travis: Make MercurialTest pass again
MercurialTest started to fail with

    abort: error: _ssl.c:510: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number

as Bitbucket disabled support for TLSv1 and TLSv1.1 [1]. In order to fix
this we need Python 2.7.9 or newer [2], but the Trusty image does only
offer Python 2.7.6. So an upgrade to the Xenial image [3] is needed,
which on the other hand only comes with Java 10 or 11 (default).
However,

[1] https://bitbucket.org/blog/deprecating-tlsv1-tlsv1-1-2018-12-01
[2] https://mercurial-scm.org/wiki/SecureConnections
[3] https://blog.travis-ci.com/2018-11-08-xenial-release