ConanFunTest: Make the version of "zlib" explicit
This resolves the following error that started to appear:

    ERROR: Conflict in libxml2/2.9.12:

    'libxml2/2.9.12' requires 'zlib/1.2.12' while 'libcurl/7.80.0'
    requires 'zlib/1.2.11'.

    To fix this conflict you need to override the package 'zlib' in your
    root package.

Note that aligning on the older version 1.2.11 did not make the error go
away, and the new version 1.2.12 lacks source artifact metadata.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>